# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyBestList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'

  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'

  # Pods for MyBestList

end
