# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MMVM-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MMVM-sample
pod 'Alamofire'
  target 'MMVM-sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MMVM-sampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
