# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target '11_04_Gerenciador_Bibliotecas' do
  use_frameworks!

  # Pods for 11_04_Gerenciador_Bibliotecas
  pod 'Kingfisher', '~> 5.0'


end
